version: 2.1

workflows:
  version: 2.1
  lib-compile:
    jobs:
      - compile
      - test:
          requires: 
            - compile

jobs:
  compile:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: 
          name: make lib
          command: cd ./src && make lib
      - run:
          name: make test
          command: cd ./test && make all
      - persist_to_workspace:
          root: test

  test:
    docker:
      - image: gcc:8.2
    steps:
      - attach_workspace:
          at: test
      - run:
          name: run tests
          command: ./test/test.exe

