version: 2.1

workflows:
  version: 2.1
  compile_and_test:
    jobs:
      - compile_lib
      - compile_tests:
          requires:
            - compile_lib
      - run_tests:
          requires:
            - compile_tests

jobs:
  compile_lib:
    docker:
      - image: gcc:8.2
    steps:
      - checkout
      - run: cd ./src && make lib
      - run: mkdir output && mv src/libtestfunctions.a output
      - run: mkdir output/test && mv test output/test
      - run: ls -la
      - persist_to_workspace:
          root: output
          paths:
            - "*.a"
  
  compile_tests:
    docker:
      - image: gcc:8.2
    steps:
      - attach_workspace:
          at: output
      - run: ls -la
      - run: mv output/* src
      - run: cd ./test && make all
      - persist_to_workspace:
          root: exe
          paths:
            - "*.exe"

  run_tests:
    docker:
      - image: gcc:8.2
    steps:
      - attach_workspace:
          at: exe
      - run: exe/test.exe

